
# Don't exclude nginx.conf, needs to be copied into _site for
# cloud.gov to pick up on it.
exclude:
- ".gitignore"
- todo.txt
- Gemfile
- Gemfile.lock
- Makefile
- Staticfile
- README.md
- CONTRIBUTING.md
- LICENSE.md
- dap.md
- uxtesting.md
- ".sass-cache"
- requirements.txt
- system-security-plan.yml
- manifest.yml
- vendor
- .codeclimate.yml
- .eslinrc.yml
- bin/
- docs/
- Dockerfile
- Dockerfile.production
- docker-compose.yml
- make.ps1

# defaults
defaults:
  -
    scope:
      path: ""
      type: agencies
    values:
      layout: default

collections:
  agencies:
    output: true
    permalink: /:path/
  data_pages:
    output: true
    permalink: /:path/data/

# Site title and description
title: "Cook County Analytics | Cook County web traffic."
description: "Analytics data for Cook County. This is an alpha version."

# Site's own URL
url: http://analytics.cookcountyil.gov

# Default dropdown title, will not appear if there are no sub-pages
dropdown_title: Cook County Website

# Default data url (also needs to be in nginx.conf for cloud.gov deployment)
data_url: http://analytics.cookcountyil.gov/data



# twitter information
twitter: cookcountytech

# Site wide error message
site_wide_error:
  display: false
  title: "Error message title here"
  body: "Put the error message body here"

sass:
  sass_dir: sass
  style: nested
